name: My First Github Action
on: [push]
jobs: 
    print-hello-world1:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world!!!"
            - run: echo "this is step no 2"